ki/2022-03
Adventech/sabbath-school-lessons pull request #1892
Opened 2022-08-23 23:05 UTC by Burkifa23

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [_] Have you run `run.sh` or `node deploy.js -b test -l [language] -q [quarter]`? While running node some dependencies were deprecated.
- [x] Have you checked for semicolons in the titles?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

For example, `./run.sh -l en -q 2022-01` or `node deploy.js -b test -l en -q 2018-02`.

### Description of contribution

Reach out to me for any concerns.

2022-08-30 02:42 UTC, imasaru commented
Thanks, Frank!
We could consider changing the language code to the [official](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=236) `kin` to avoid conflict with Kikuyu, the language granted the `ki` code in [ISO 639](https://en.wikipedia.org/wiki/ISO_639). 

@alimness @VitalikL thoughts? :-)

2022-08-30 11:19 UTC, Burkifa23 commented
Okay, I'm done changing it from ki to kin.

On Tue, Aug 30, 2022 at 2:42 AM Evan ***@***.***> wrote:

> Thanks, Frank!
> We could consider changing the language code to the official
> <https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=236>
> kin to avoid conflict with Kikuyu, the language granted the ki code in ISO
> 639 <https://en.wikipedia.org/wiki/ISO_639>.
>
> @alimness <https://github.com/alimness> @VitalikL
> <https://github.com/VitalikL> thoughts? :-)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Adventech/sabbath-school-lessons/pull/1892#issuecomment-1231075816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXGASRV7Z3MBACNKMLYUXA3V3VYJRANCNFSM57NHSQ6A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-12 13:20 UTC, VitalikL commented
Thanks @Burkifa23 ! As we are now official GC app, we need to confirm the source of the translation of the lesson. Is this an official translation of the lesson?

2022-09-12 14:31 UTC, Burkifa23 commented
> Thanks @Burkifa23 ! As we are now an official GC app, we need to confirm the source of the translation of the lesson. Is this an official translation of the lesson?

Yes, it is translated by the Rwandan SDA church which I scanned. I do understand your concerns sadly there is no digital version. I had tried checking from [Sabbath school personal ministries archives](https://www.sabbathschoolpersonalministries.org/archives) but I did not find it there except on a Facebook group that posts the lessons daily called [IBYIGISHO BY'ISHURI RYO KU ISABATO](https://www.facebook.com/groups/1188338784852006/) which may be the only way to vouch for kin/2022-03. If you want I can send you the scanned pdf file.

2022-09-12 16:52 UTC, VitalikL commented
@Burkifa23 Great! Yes, if you can provide the PDF, just in case GC will have any questions / concerns. I will add the Bible translation and work on merging your PR. Thanks for contribution!

2022-09-12 18:00 UTC, Burkifa23 commented
In case you don't receive the file or someone else wants the file, You can reach it from [grosfi.ch/V9m7mLUgNAw](https://www.grosfichiers.com/V9m7mLUgNAw). I was amazed by the bible passage reference parser so adding the bible verses would be very wonderful and if you need further help I will be available.  Although, I don't know CoffeeScript I can help in other ways. Note to use the  Bibiliya Yera (BYSB) as the bible version in order to get the 66 books as other versions either have more books or have outdated translations.

2022-09-12 18:08 UTC, VitalikL commented
Thanks @Burkifa23 ! Just to confirm is this https://en.wikipedia.org/wiki/Kinyarwanda language? Because it seems like we can use `rw` language code for that.

2022-09-12 19:37 UTC, Burkifa23 commented
> Thanks @Burkifa23 ! Just to confirm is this https://en.wikipedia.org/wiki/Kinyarwanda language? Because it seems like we can use `rw` language code for that.

@VitalikL  that is Kinyarwanda. We can use  [rw] according to ISO 639-1 or [kin] according to ISO 639-2. Do you want me to change to [rw] or remain on [kin]?

2022-09-29 14:27 UTC, VitalikL requested changes

2022-09-29 14:27 UTC, VitalikL commented on src/kin/2022-03/01/01.md
> +>“Asubiza intege mu bugingo bwanjye, anyobora inzira yo gukiranuka ku bw’izina rye”. (Zaburi 23:3).
@Burkifa23 Please see en/2022-04/01/01.md to see how to properly format Sabbath day

2022-09-29 14:27 UTC, VitalikL commented on src/kin/2022-03/01/02.md
> +
Extra line here

2022-09-29 14:27 UTC, VitalikL commented on src/kin/2022-03/01/02.md
> +date: KU WA MBERE 26 KAMENA
Date has to be a properly formatted date, see English version

2022-09-29 14:27 UTC, VitalikL commented on src/kin/2022-03/01/02.md
> +`Bisobanuye iki kuri wowe kumenya ko hari ukwitayeho kandi ugukunda umeze atyo ? Ni mu buhe buryo wakoresha iyo shusho ngo usubizemo intege umuntu utagifitiye Imana icyizere kubera ingorane yahuye na
Here, questions should be separated by the new line.

2022-09-29 14:29 UTC, VitalikL commented
@Burkifa23 I am not sure if you were creating files manually, but they are not currently in a format that would work for the app. Especially dates, have to be in a proper format. You can use `create.js` script to generate the structure for the quarterly.

Additionally, please remove `package-lock.json` from the commits

2022-09-29 18:43 UTC, Burkifa23 commented
Hello VitalikL
I want to add that I am not a church employee but just a member. My
motivation to have this language posted is that it is spoken by almost a
million Adventists worldwide and it pains me that it is not found on the
application.

I want to understand the approval process before the language is posted on
the app.

My father consulted the head of the translation department at the union
level asking him if he could support us. But the answer was, the problem is
known by the Union.

What is the likelihood that my contributions will be taken into
consideration?

Do you have a time frame between the first submission and the posting on
the app?

Sincerely,
Frank.

On Thu, Sep 29, 2022 at 6:25 PM kwizera frank ***@***.***>
wrote:

> Hello VitalikL,
> I did create the files manually because I didn't know how to use
> create.js.  I realized that  English dates are used even in other languages
> so I will apply the same changes to even the fourth quarter which
> am preparing.
>
> On Thu, Sep 29, 2022 at 2:29 PM VitalikL ***@***.***> wrote:
>
>> @Burkifa23 <https://github.com/Burkifa23> I am not sure if you were
>> creating files manually, but they are not currently in a format that would
>> work for the app. Especially dates, have to be in a proper format. You can
>> use create.js script to generate the structure for the quarterly.
>>
>> Additionally, please remove package-lock.json from the commits
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Adventech/sabbath-school-lessons/pull/1892#issuecomment-1262367092>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXGASRSWKCFPO6V22WVLFALWAWRT7ANCNFSM57NHSQ6A>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-09-30 17:07 UTC, Burkifa23 commented
All previous mistakes were fixed. Week 1- 2 of 2022-04 is ready.

2022-10-11 08:10 UTC, Burkifa23 commented
Hello VitalikL,
I did create the files manually because I didn't know how to use
create.js.  I realized that  English dates are used even in other languages
so I will apply the same changes to even the fourth quarter which
am preparing.

On Thu, Sep 29, 2022 at 2:29 PM VitalikL ***@***.***> wrote:

> @Burkifa23 <https://github.com/Burkifa23> I am not sure if you were
> creating files manually, but they are not currently in a format that would
> work for the app. Especially dates, have to be in a proper format. You can
> use create.js script to generate the structure for the quarterly.
>
> Additionally, please remove package-lock.json from the commits
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Adventech/sabbath-school-lessons/pull/1892#issuecomment-1262367092>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXGASRSWKCFPO6V22WVLFALWAWRT7ANCNFSM57NHSQ6A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-11 14:55 UTC, VitalikL commented
Ooops! Looks like you have to fix some issues before I can merge this PR
||Error description |
| ----------- | ----------- |
|🛑| Critical error. Can not parse the quarterly info: `src/kin/2022-04`/info.yml. Error: `YAMLException: bad indentation of a mapping entry (19:16)<br><br> 16 |     - name: Ushinzwe Imirimo yo Gusohora Inyandiko<br> 17 |       value: "Lea Alexander Greve"<br> 18 |     - name: Ushinzwe Ubwanditsi Wungirije<br> 19 |       value: ""Sharon Thomas-Crews"<br>---------------------^`|

2022-11-11 16:15 UTC, Burkifa23 commented
@VitalikL Hi ! Hope you are doing well.
Where are the errors so that I can correct them, if possible?  I would appreciate it very much if you helped me with it.

2022-11-11 17:24 UTC, VitalikL commented
Hi @Burkifa23. I was able to work on it on my end (Quarter 4, 2022. plus added the Bible so the links would be clickable). Can you please sync your fork and create Pull Request for new lessons (days) that are empty for this quarter. I also made formatting adjustments to the content for kin/2022-04 - please follow that format. And for now, I will close this PR. Thank you for your contribution

2022-11-11 17:24 UTC, closed without merging